'use client';

import { useEffect, useMemo, useState } from 'react';
import { PLANETS, PLANET_META, formatDateLabel, getDateRange, getDegreeCategory, getStats, latestByPlanet, parseReversalData, recordsForDate } from '@/lib/reversal/parser';

const initialFilters = { search: '', planet: 'All', session: 'All', minDegree: '', maxDegree: '', fromDate: '', toDate: '' };

function updateQuery(date, planet) {
  const params = new URLSearchParams(window.location.search);
  params.set('date', date);
  if (planet && planet !== 'All') params.set('planet', planet.toLowerCase()); else params.delete('planet');
  window.history.pushState({}, '', `${window.location.pathname}?${params.toString()}`);
}

function Section({ id, eyebrow, title, children, className = '' }) {
  return <section id={id} className={`reversal-section ${className}`}><div className="reversal-section-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div></div>{children}</section>;
}

function StatCard({ icon, label, value }) { return <article className="reversal-stat-card"><i className={`bi ${icon}`} aria-hidden="true" /><span>{label}</span><strong>{value}</strong></article>; }
function PlanetLabel({ planet, quality = PLANET_META[planet]?.quality }) { return <><span className="reversal-planet-icon" aria-hidden="true">{PLANET_META[planet]?.icon || '✦'}</span><span><b>{planet}</b><small>{quality}</small></span></>; }

function Timeline({ record }) {
  if (!record) return null;
  return <div className="reversal-timeline" title="Trade Time is 15 minutes before Reversal Time according to this dataset's convention"><div><strong>{record.tradeTime}</strong><span>TRADE</span></div><div className="timeline-line"><i /> <small>15 MIN</small> <i /></div><div><strong>{record.reversalTime}</strong><span>REVERSAL</span></div></div>;
}

export default function ReversalDashboard() {
  const [records, setRecords] = useState([]);
  const [sourceTotal, setSourceTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [date, setDate] = useState('');
  const [planet, setPlanet] = useState('All');
  const [studyMode, setStudyMode] = useState(false);
  const [filters, setFilters] = useState(initialFilters);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [degreeTarget, setDegreeTarget] = useState('29');
  const [degreeTolerance, setDegreeTolerance] = useState('1');
  const [compareA, setCompareA] = useState('Mars');
  const [compareB, setCompareB] = useState('Mercury');

  useEffect(() => {
    fetch('/data/reversal-time.json').then((response) => { if (!response.ok) throw new Error('load'); return response.json(); }).then((payload) => {
      const parsed = parseReversalData(payload);
      const params = new URLSearchParams(window.location.search);
      const dates = getDateRange(parsed);
      const requestedDate = params.get('date');
      const requestedPlanet = PLANETS.find((item) => item.toLowerCase() === params.get('planet')) || 'All';
      setRecords(parsed); setSourceTotal(payload.recordsTotal || parsed.length); setDate(dates.includes(requestedDate) ? requestedDate : dates[0] || ''); setPlanet(requestedPlanet); setLoading(false);
    }).catch(() => { setError(true); setLoading(false); });
  }, []);

  const dates = useMemo(() => getDateRange(records), [records]);
  const todayRecords = useMemo(() => recordsForDate(records, date), [records, date]);
  const selectedRecords = useMemo(() => planet === 'All' ? records : records.filter((record) => record.planet === planet), [records, planet]);
  const selectedToday = useMemo(() => todayRecords.filter((record) => planet === 'All' || record.planet === planet), [todayRecords, planet]);
  const nextReversal = selectedToday[0];
  const near30 = todayRecords.filter((record) => record.degree >= 28);
  const latest = useMemo(() => latestByPlanet(records), [records]);
  const stats = useMemo(() => getStats(selectedRecords), [selectedRecords]);
  const lastSevenDates = dates.slice(0, 7);
  const previousRecord = selectedRecords.slice().sort((a, b) => `${a.isoDate}${a.sortTime}`.localeCompare(`${b.isoDate}${b.sortTime}`)).slice(-2, -1)[0];
  const currentRecord = selectedRecords.slice().sort((a, b) => `${a.isoDate}${a.sortTime}`.localeCompare(`${b.isoDate}${b.sortTime}`)).slice(-1)[0];
  const degreeChange = currentRecord && previousRecord ? currentRecord.degree - previousRecord.degree : 0;
  const degreeResults = useMemo(() => records.map((record) => ({ record, difference: Math.abs(record.degree - Number(degreeTarget)) })).filter(({ difference }) => difference <= Number(degreeTolerance)).sort((a, b) => a.difference - b.difference).slice(0, 10), [degreeTarget, degreeTolerance, records]);
  const filteredRecords = useMemo(() => records.filter((record) => { const query = filters.search.toLowerCase(); const matchesSearch = !query || `${record.planet} ${record.quality} ${record.date} ${record.degree}`.toLowerCase().includes(query); const matchesPlanet = filters.planet === 'All' || record.planet === filters.planet; const matchesSession = filters.session === 'All' || (filters.session === 'Morning' ? record.timeMinutes < 720 : record.timeMinutes >= 720); const matchesDegree = (!filters.minDegree || record.degree >= Number(filters.minDegree)) && (!filters.maxDegree || record.degree <= Number(filters.maxDegree)); const matchesDates = (!filters.fromDate || record.isoDate >= filters.fromDate) && (!filters.toDate || record.isoDate <= filters.toDate); return matchesSearch && matchesPlanet && matchesSession && matchesDegree && matchesDates; }), [filters, records]);
  const totalPages = Math.max(1, Math.ceil(filteredRecords.length / pageSize));
  const visibleRecords = filteredRecords.slice((page - 1) * pageSize, page * pageSize);
  const chooseDate = (nextDate) => { setDate(nextDate); updateQuery(nextDate, planet); };
  const choosePlanet = (nextPlanet) => { setPlanet(nextPlanet); updateQuery(date, nextPlanet); };
  const moveDate = (direction) => { const index = dates.indexOf(date); chooseDate(dates[Math.max(0, Math.min(dates.length - 1, index + direction))]); };
  const exportRecords = (format) => { const content = format === 'json' ? JSON.stringify(filteredRecords.map((record) => record.source), null, 2) : [['Date', 'Planet', 'Quality', 'Degree', 'Trade Time', 'Reversal Time'], ...filteredRecords.map((record) => [record.date, record.planet, record.quality, record.degree, record.tradeTime, record.reversalTime])].map((row) => row.join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: format === 'json' ? 'application/json' : 'text/csv' })); link.download = `reversal-time.${format}`; link.click(); URL.revokeObjectURL(link.href); };

  if (loading) return <main className="container-fluid tool-page reversal-page"><div className="reversal-loading" role="status"><span className="spinner-border spinner-border-sm" /> Loading reversal study data...</div></main>;
  if (error) return <main className="container-fluid tool-page reversal-page"><div className="reversal-empty" role="alert"><i className="bi bi-exclamation-triangle" /><strong>Unable to load reversal data.</strong><span>Please try again.</span><button className="btn gold-action" type="button" onClick={() => window.location.reload()}>Retry</button></div></main>;

  const dateIndex = dates.indexOf(date);
  return <main className="container-fluid tool-page reversal-page">
    <header className="reversal-header"><div><div className="eyebrow">ASTRO MARKET RESEARCH</div><h1 className="page-title">🔄 Reversal Time</h1><p className="page-subtitle">Planet-wise reversal timing, degree and trade time</p></div><div className="reversal-header-actions"><label className="study-toggle"><input type="checkbox" checked={studyMode} onChange={(event) => setStudyMode(event.target.checked)} /> <span>📘 Study Mode</span></label><button className="outline-action" type="button" onClick={() => window.location.reload()}><i className="bi bi-arrow-clockwise" /> Refresh</button></div></header>
    <nav className="reversal-quick-nav" aria-label="Reversal sections"><a href="#today">Today</a><a href="#planets">Planets</a><a href="#timeline">Timeline</a><a href="#history">History</a><a href="#degree">Degree</a><a href="#compare">Compare</a><a href="#calendar">Calendar</a></nav>
    <div className="alert reversal-info"><strong><i className="bi bi-info-circle" /> How to read</strong><span>Reversal Time = recorded planetary reversal/end time. Trade Time = 15 minutes before Reversal Time. This page is for historical study and research only.</span></div>
    <section className="reversal-date-nav" aria-label="Date navigation"><button className="subtle-action" type="button" onClick={() => moveDate(1)} disabled={dateIndex >= dates.length - 1}><i className="bi bi-chevron-left" /> Previous</button><div><input aria-label="Selected date" type="date" value={date} onChange={(event) => dates.includes(event.target.value) && chooseDate(event.target.value)} /><strong>{formatDateLabel(date, { day: '2-digit', month: 'short', year: 'numeric' })}</strong><small>{formatDateLabel(date, { weekday: 'long' })}</small></div><button className="gold-action" type="button" onClick={() => chooseDate(dates[0])}>Today</button><button className="subtle-action" type="button" onClick={() => moveDate(-1)} disabled={dateIndex <= 0}>Next <i className="bi bi-chevron-right" /></button></section>
    <section className="row g-3 mb-4" aria-label="At a glance"><div className="col-6 col-xl-3"><StatCard icon="bi-stars" label="PLANETS" value={PLANETS.length} /></div><div className="col-6 col-xl-3"><StatCard icon="bi-arrow-repeat" label="TODAY'S REVERSALS" value={todayRecords.length} /></div><div className="col-6 col-xl-3"><StatCard icon="bi-fire" label="NEAR 30°" value={near30.length} /></div><div className="col-6 col-xl-3"><StatCard icon="bi-stopwatch" label="NEXT REVERSAL" value={nextReversal?.reversalTime || 'No record'} /></div></section>
    <Section id="today" eyebrow="PRIMARY OBSERVATION" title="Next Reversal"><div className="next-reversal-card">{nextReversal ? <><div className="next-reversal-identity"><PlanetLabel planet={nextReversal.planet} quality={nextReversal.quality} /><strong>{nextReversal.degree.toFixed(2)}°</strong></div><Timeline record={nextReversal} /><span className="status-badge trading-status">Upcoming</span></> : <div className="reversal-empty">No reversal records for this date.</div>}</div></Section>
    <Section id="today-status" eyebrow="SELECTED DATE" title="Today's Planet Status"><div className="row g-3">{PLANETS.map((item) => { const record = todayRecords.find((entry) => entry.planet === item); return <div className="col-12 col-sm-6 col-lg-3" key={item}><button type="button" className={`today-planet-card ${planet === item ? 'selected' : ''}`} onClick={() => choosePlanet(item)}><PlanetLabel planet={item} quality={record?.quality || PLANET_META[item].quality} />{record ? <><strong className="today-degree">{record.degree.toFixed(2)}°</strong><span>{record.reversalTime}</span><small>Trade {record.tradeTime} · {getDegreeCategory(record.degree)}</small></> : <span className="no-record">No reversal</span>}</button></div>; })}</div></Section>
    <Section id="planets" eyebrow="FILTER BY PLANET" title="Planet Selector"><div className="planet-selector">{['All', ...PLANETS].map((item) => <button type="button" className={planet === item ? 'active' : ''} key={item} onClick={() => choosePlanet(item)}>{item === 'All' ? '✦' : PLANET_META[item].icon}<span>{item}</span><small>{item === 'All' ? records.length : records.filter((record) => record.planet === item).length} records</small></button>)}</div></Section>
    {planet !== 'All' && <Section eyebrow="PLANET DETAIL" title={`${PLANET_META[planet].icon} ${planet}`}><div className="row g-3"><div className="col-6 col-lg-3"><StatCard label="Degree" value={currentRecord ? `${currentRecord.degree.toFixed(2)}°` : '—'} icon="bi-bullseye" /></div><div className="col-6 col-lg-3"><StatCard label="Trade" value={currentRecord?.tradeTime || '—'} icon="bi-clock" /></div><div className="col-6 col-lg-3"><StatCard label="Reversal" value={currentRecord?.reversalTime || '—'} icon="bi-arrow-repeat" /></div><div className="col-6 col-lg-3"><StatCard label="Average Degree" value={`${stats.average.toFixed(2)}°`} icon="bi-bar-chart" /></div></div><button className="subtle-action mt-3" type="button" onClick={() => choosePlanet('All')}><i className="bi bi-arrow-left" /> Back to All Planets</button></Section>}
    {currentRecord && <><Section id="timeline" eyebrow="TRADE CONVENTION" title="Trade → Reversal Timeline"><Timeline record={currentRecord} /></Section><Section id="degree" eyebrow="DEGREE POSITION STUDY" title="Degree Meter"><div className="degree-meter-label"><span>0°</span><strong>{currentRecord.degree.toFixed(2)}° / 30°</strong><span>30°</span></div><div className="degree-meter"><i style={{ left: `${Math.min(100, currentRecord.degree / 30 * 100)}%` }} /></div><span className="degree-category">{getDegreeCategory(currentRecord.degree)}</span>{studyMode && <p className="study-note">Degree position represented in the supplied historical dataset.</p>}</Section></>}
    <Section eyebrow="WATCH LIST" title="🔥 Near 30° Watch"><div className="near30-grid">{records.filter((record) => record.degree >= 28).slice(0, 12).map((record) => <button type="button" key={record.id} onClick={() => chooseDate(record.isoDate)}><PlanetLabel planet={record.planet} quality={record.quality} /><strong>{record.degree.toFixed(2)}°</strong><span>{record.date} · Near 30°</span></button>)}</div><p className="study-note">Degree-position study only.</p></Section>
    {planet !== 'All' && <Section eyebrow="CHANGE OVER TIME" title="🧠 What Changed?"><div className="change-card"><PlanetLabel planet={planet} quality={PLANET_META[planet].quality} /><div><span>Previous</span><strong>{previousRecord ? `${previousRecord.degree.toFixed(2)}°` : '—'}</strong><small>{previousRecord?.date || ''}</small></div><div><span>Current</span><strong>{currentRecord ? `${currentRecord.degree.toFixed(2)}°` : '—'}</strong><small>{currentRecord?.date || ''}</small></div><div><span>Change</span><strong className={degreeChange >= 0 ? 'text-success' : 'text-warning'}>{previousRecord ? `${degreeChange >= 0 ? '+' : ''}${degreeChange.toFixed(2)}°` : '—'}</strong><small>{previousRecord ? (Math.abs(degreeChange) < .01 ? 'No significant change' : degreeChange > 0 ? 'Increased' : 'Decreased') : ''}</small></div></div></Section>}
    <Section eyebrow="RECENT HISTORY" title="Last 7 Days"><div className="last-seven-list">{lastSevenDates.map((item) => <button type="button" key={item} onClick={() => chooseDate(item)}><strong>{formatDateLabel(item, { day: '2-digit', month: 'short' })}</strong><span>{recordsForDate(records, item).map((record) => `${PLANET_META[record.planet].icon} ${record.planet} ${record.degree.toFixed(2)}° · ${record.reversalTime}`).join('  ')}</span></button>)}</div></Section>
    <Section eyebrow="LATEST AVAILABLE" title="🏆 Latest Reversal by Planet"><div className="row g-3">{PLANETS.map((item) => { const record = latest.find((entry) => entry.planet === item); return <div className="col-12 col-sm-6 col-lg-3" key={item}><article className="latest-planet-card"><PlanetLabel planet={item} />{record ? <><strong>{record.degree.toFixed(2)}°</strong><span>{record.date} · {record.reversalTime}</span></> : <span>No record</span>}</article></div>; })}</div></Section>
    {planet !== 'All' && <Section eyebrow="HISTORICAL JOURNEY" title={`${PLANET_META[planet].icon} ${planet} Degree Journey`}><div className="journey-list">{selectedRecords.slice().reverse().slice(0, 10).map((record) => <div key={record.id}><span>{record.date}</span><strong>{record.degree.toFixed(2)}°</strong><i style={{ width: `${record.degree / 30 * 100}%` }} /></div>)}</div></Section>}
    <Section eyebrow="PLANET STATISTICS" title={planet === 'All' ? 'All Records Statistics' : `${planet} Statistics`}><div className="row g-3">{[['Records', stats.count], ['Average Degree', `${stats.average.toFixed(2)}°`], ['Minimum Degree', `${stats.min.toFixed(2)}°`], ['Maximum Degree', `${stats.max.toFixed(2)}°`], ['Morning', stats.morning], ['Afternoon', stats.afternoon]].map(([label, value]) => <div className="col-6 col-md-4 col-xl-2" key={label}><StatCard label={label} value={value} icon="bi-bar-chart" /></div>)}</div></Section>
    <Section eyebrow="MONTHLY OVERVIEW" title="Monthly Summary"><div className="monthly-bars">{PLANETS.map((item) => { const count = records.filter((record) => record.planet === item && record.isoDate.startsWith(date.slice(0, 7))).length; const max = Math.max(1, ...PLANETS.map((name) => records.filter((record) => record.planet === name && record.isoDate.startsWith(date.slice(0, 7))).length)); return <div key={item}><span>{item}</span><div className="progress"><div className="progress-bar" style={{ width: `${count / max * 100}%` }} /></div><strong>{count}</strong></div>; })}</div></Section>
    <Section eyebrow="DEGREE SEARCH" title="🔎 Find Degree"><div className="row g-3 align-items-end mb-3"><div className="col-6 col-md-3"><label htmlFor="degree-target">Target Degree</label><input id="degree-target" className="form-control" type="number" value={degreeTarget} onChange={(event) => setDegreeTarget(event.target.value)} /></div><div className="col-6 col-md-3"><label htmlFor="degree-tolerance">Tolerance ±</label><input id="degree-tolerance" className="form-control" type="number" value={degreeTolerance} onChange={(event) => setDegreeTolerance(event.target.value)} /></div></div><div className="search-results">{degreeResults.map(({ record, difference }) => <button type="button" key={record.id} onClick={() => chooseDate(record.isoDate)}><strong>{record.degree.toFixed(2)}° {record.planet}</strong><span>{record.date} · {record.reversalTime} · Difference {difference.toFixed(2)}°</span></button>)}</div></Section>
    <Section id="compare" eyebrow="SIDE-BY-SIDE STUDY" title="⚖️ Compare Planets"><div className="row g-3 mb-3"><div className="col-6"><label htmlFor="compare-a">Planet A</label><select id="compare-a" className="form-select" value={compareA} onChange={(event) => setCompareA(event.target.value)}>{PLANETS.map((item) => <option key={item}>{item}</option>)}</select></div><div className="col-6"><label htmlFor="compare-b">Planet B</label><select id="compare-b" className="form-select" value={compareB} onChange={(event) => setCompareB(event.target.value)}>{PLANETS.map((item) => <option key={item}>{item}</option>)}</select></div></div><div className="compare-grid">{[compareA, compareB].map((item) => { const itemStats = getStats(records.filter((record) => record.planet === item)); const itemLatest = latest.find((record) => record.planet === item); return <article key={item}><PlanetLabel planet={item} /><strong>{itemLatest?.degree.toFixed(2) || '—'}°</strong><span>{itemLatest?.reversalTime || '—'}</span><small>Average {itemStats.average.toFixed(2)}° · {itemStats.count} records</small></article>; })}</div></Section>
    <Section id="calendar" eyebrow="DATE MAP" title="📅 Calendar View"><div className="calendar-grid">{dates.slice().reverse().map((item) => <button type="button" className={item === date ? 'selected' : ''} key={item} onClick={() => chooseDate(item)}><strong>{formatDateLabel(item, { day: '2-digit' })}</strong><span>{recordsForDate(records, item).length} reversal{recordsForDate(records, item).length === 1 ? '' : 's'}</span></button>)}</div></Section>
    <Section eyebrow="ADVANCED FILTERS" title="🔎 Advanced Filters"><div className="row g-3"><div className="col-12 col-md-4"><label htmlFor="history-search">Search</label><input id="history-search" className="form-control" value={filters.search} onChange={(event) => { setFilters({ ...filters, search: event.target.value }); setPage(1); }} placeholder="Planet, date or degree" /></div><div className="col-6 col-md-2"><label htmlFor="history-planet">Planet</label><select id="history-planet" className="form-select" value={filters.planet} onChange={(event) => setFilters({ ...filters, planet: event.target.value })}><option>All</option>{PLANETS.map((item) => <option key={item}>{item}</option>)}</select></div><div className="col-6 col-md-2"><label htmlFor="history-session">Session</label><select id="history-session" className="form-select" value={filters.session} onChange={(event) => setFilters({ ...filters, session: event.target.value })}><option>All</option><option>Morning</option><option>Afternoon</option></select></div><div className="col-6 col-md-2"><label htmlFor="history-min">Min Degree</label><input id="history-min" className="form-control" type="number" value={filters.minDegree} onChange={(event) => setFilters({ ...filters, minDegree: event.target.value })} /></div><div className="col-6 col-md-2"><label htmlFor="history-max">Max Degree</label><input id="history-max" className="form-control" type="number" value={filters.maxDegree} onChange={(event) => setFilters({ ...filters, maxDegree: event.target.value })} /></div></div><div className="d-flex flex-wrap justify-content-between gap-2 mt-3"><span className="grah-result-count">{filteredRecords.length} filtered records</span><div className="d-flex gap-2"><button className="subtle-action" type="button" onClick={() => { setFilters(initialFilters); setPage(1); }}>Reset</button><button className="gold-action" type="button" onClick={() => exportRecords('csv')}><i className="bi bi-download" /> Export CSV</button><button className="subtle-action" type="button" onClick={() => exportRecords('json')}>Export JSON</button></div></div></Section>
    <Section id="history" eyebrow="DETAILED RESEARCH" title="Full History"><div className="table-responsive"><table className="table reversal-history-table"><thead><tr><th>#</th><th>Date</th><th>Planet</th><th>Quality</th><th>Degree</th><th>Trade</th><th>Reversal</th></tr></thead><tbody>{visibleRecords.map((record) => <tr key={record.id}><td>{record.source.DT_RowIndex}</td><td>{record.date}</td><td>{record.planet}</td><td>{record.quality}</td><td>{record.degree.toFixed(2)}°</td><td>{record.tradeTime}</td><td>{record.reversalTime}</td></tr>)}</tbody></table></div><div className="grah-pagination"><span>Showing {filteredRecords.length ? (page - 1) * pageSize + 1 : 0}-{Math.min(page * pageSize, filteredRecords.length)} of {filteredRecords.length}</span><div className="btn-group"><button className="subtle-action" type="button" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><button className="subtle-action" type="button" disabled={page === totalPages} onClick={() => setPage(page + 1)}>Next</button></div></div></Section>
    <aside className="alert reversal-disclaimer"><strong>Educational / Research Use Only</strong><p className="mb-0">This page displays historical planetary reversal-time data for study and analysis. It does not provide guaranteed market predictions, trading signals, financial advice or investment recommendations.</p></aside>
  </main>;
}
